"use client";
import * as React from "react";
import Box from "@mui/material/Box"; import Button from "@mui/material/Button"; import Card from "@mui/material/Card"; import LinearProgress from "@mui/material/LinearProgress"; import Typography from "@mui/material/Typography"; import UploadFileIcon from "@mui/icons-material/UploadFile"; import CameraAltOutlinedIcon from "@mui/icons-material/CameraAltOutlined"; import ArrowForwardIcon from "@mui/icons-material/ArrowForward"; import CheckIcon from "@mui/icons-material/Check"; import { useRouter, useSearchParams } from "next/navigation"; import Stack from "@/components/lumina-stack";
import { worksheets } from "@/lib/student-mock-data"; import PageReview from "@/components/submissions/PageReview"; import OcrReview from "@/components/submissions/OcrReview"; import { correctOcrExtraction, createOcrDocument, releasePagePreview, validateUploadFiles, type OcrPage, type UploadPage } from "@/services/submissions";
const button = { minHeight: 42, textTransform: "none", borderRadius: "10px" }; const primary = { ...button, bgcolor: "#9E3A24", color: "#FFFDFA", "&:hover": { bgcolor: "#8A3120" } }; const secondary = { ...button, borderColor: "#E4DCD0", color: "#2A2622", bgcolor: "#FFFDFA" };
function UploadWizard() { const router = useRouter(); const params = useSearchParams(); const incomplete = worksheets.filter((w) => w.status === "incomplete"); const [step, setStep] = React.useState(1); const [selectedId, setSelectedId] = React.useState(params.get("ws") || incomplete[0]?.id || ""); const [pages, setPages] = React.useState<UploadPage[]>([]); const [ocrPages,setOcrPages]=React.useState<OcrPage[]>([]); const [errors, setErrors] = React.useState<string[]>([]); const [dragOver, setDragOver] = React.useState(false); const [uploading, setUploading] = React.useState(false); const [progress, setProgress] = React.useState(0); const selected = incomplete.find((w) => w.id === selectedId) || incomplete[0];
 const add = (files: File[]) => { const result = validateUploadFiles(files, pages); setPages((current) => [...current, ...result.pages]); setErrors(result.errors); };
 const move = (id: string, direction: -1 | 1) => setPages((current) => { const index = current.findIndex((p) => p.id === id); const next = index + direction; if (index < 0 || next < 0 || next >= current.length) return current; const copy = [...current]; [copy[index], copy[next]] = [copy[next], copy[index]]; return copy; });
 const remove = (id: string) => setPages((current) => { const page = current.find((p) => p.id === id); if (page) releasePagePreview(page); return current.filter((p) => p.id !== id); });
 const replace = (id: string, file: File) => { const old = pages.find((p) => p.id === id); if (!old) return; const result = validateUploadFiles([file], pages.filter((p) => p.id !== id)); if (result.errors.length) { setErrors(result.errors); return; } releasePagePreview(old); setPages((current) => current.map((p) => p.id === id ? result.pages[0] : p)); };
 const submit = async () => { setUploading(true); setErrors([]); setProgress(0); try { const result=await createOcrDocument({studentId:Number(params.get("studentId")||1),worksheetId:Number(selectedId.replace(/\D/g,"")),pages}); setOcrPages(result.pages);setProgress(100);setStep(4); } catch (error) { setErrors([error instanceof Error ? error.message : "Upload failed. Please try again."]); } finally { setUploading(false); } };
 return <Box sx={{ minHeight: "100vh", bgcolor: "#F7F4EF", px: { xs: 2, sm: 4 }, py: 4 }}><Box sx={{ maxWidth: 850, mx: "auto" }}><Typography sx={{ fontSize: 12, letterSpacing: ".1em", color: "#6F675E", mb: 3 }}>STEP {step} OF 4</Typography>
 {step === 1 && <><Typography component="h1" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 31, mb: 2 }}>Which worksheet are you submitting?</Typography><Stack gap={1.25}>{incomplete.map((w) => <Card component="button" key={w.id} onClick={() => setSelectedId(w.id)} aria-pressed={selectedId === w.id} variant="outlined" sx={{ textAlign: "left", p: 2, borderColor: selectedId === w.id ? "#9E3A24" : "#EBE4D9", bgcolor: "#FFFDFA" }}><Typography sx={{ fontWeight: 700 }}>{w.title}</Typography><Typography sx={{ fontSize: 12, color: "#6F675E" }}>{w.topic}</Typography></Card>)}</Stack><Stack direction="row" justifyContent="flex-end" sx={{ mt: 3 }}><Button onClick={() => setStep(2)} endIcon={<ArrowForwardIcon />} sx={primary}>Continue</Button></Stack></>}
 {step === 2 && <><Typography component="h1" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 31 }}>Upload your pages</Typography><Typography sx={{ mb: 2, color: "#4A443D" }}>For {selected?.title}. Add JPG, PNG, or PDF files. You can add multiple photos.</Typography><Box onDragOver={(e) => { e.preventDefault(); setDragOver(true); }} onDragLeave={() => setDragOver(false)} onDrop={(e) => { e.preventDefault(); setDragOver(false); add(Array.from(e.dataTransfer.files)); }} sx={{ border: "2px dashed", borderColor: dragOver ? "#9E3A24" : "#DCCFBE", borderRadius: 2, p: 4, textAlign: "center", bgcolor: "#FFFDFA" }}><UploadFileIcon /><Typography sx={{ fontWeight: 700 }}>Drag and drop files here</Typography><Stack direction="row" justifyContent="center" gap={1} sx={{ mt: 2 }}><Button component="label" variant="outlined" sx={secondary}>Choose files<input hidden type="file" multiple accept="image/jpeg,image/png,application/pdf" onChange={(e) => { add(Array.from(e.currentTarget.files || [])); e.currentTarget.value = ""; }} /></Button><Button component="label" variant="outlined" startIcon={<CameraAltOutlinedIcon />} sx={secondary}>Take photo<input hidden type="file" accept="image/*" capture="environment" onChange={(e) => { add(Array.from(e.currentTarget.files || [])); e.currentTarget.value = ""; }} /></Button></Stack><Typography sx={{ fontSize: 12, color: "#6F675E", mt: 2 }}>Up to 20 MB per file</Typography></Box>{errors.length > 0 && <Box role="alert" sx={{ color: "#B4573F", mt: 2 }}>{errors.map((error) => <Typography key={error}>{error}</Typography>)}</Box>}<Typography sx={{ mt: 2, fontSize: 12, letterSpacing: ".1em" }}>{pages.length} PAGE{pages.length === 1 ? "" : "S"} DETECTED</Typography>{pages.length > 0 && <PageReview pages={pages} onMove={move} onRotate={(id) => setPages((current) => current.map((p) => p.id === id ? { ...p, rotation: ((p.rotation + 90) % 360) as UploadPage["rotation"] } : p))} onRemove={remove} onReplace={replace} />}<Stack direction="row" justifyContent="space-between" sx={{ mt: 3 }}><Button onClick={() => setStep(1)} variant="outlined" sx={secondary}>Back</Button><Button onClick={() => pages.length ? setStep(3) : setErrors(["Add at least one page before reviewing your submission."])} sx={primary}>Review submission</Button></Stack></>}
 {step === 3 && <><Typography component="h1" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 31 }}>Ready to submit?</Typography><Card variant="outlined" sx={{ p: 2, my: 2, bgcolor: "#FFFDFA" }}><Typography sx={{ fontWeight: 700 }}>{selected?.title}</Typography><Typography>{pages.length} page{pages.length === 1 ? "" : "s"} ready for AI marking</Typography></Card>{errors.length > 0 && <Typography role="alert" sx={{ color: "#B4573F" }}>{errors[0]}</Typography>}{uploading && <><Typography sx={{ mt: 2 }}>Uploading {Math.ceil(progress / 100 * pages.length) || 1} of {pages.length} pages…</Typography><LinearProgress variant="determinate" value={progress} sx={{ mt: 1 }} /></>}<Stack direction="row" justifyContent="space-between" sx={{ mt: 3 }}><Button onClick={() => setStep(2)} disabled={uploading} variant="outlined" sx={secondary}>Back</Button><Button onClick={() => void submit()} disabled={uploading} sx={primary}>{uploading ? "Uploading…" : "Submit for AI Marking"}</Button></Stack></>}
 {step === 4 && <Box sx={{py:2}}><OcrReview pages={ocrPages} onCorrect={async(id,text)=>{const updated=await correctOcrExtraction(id,text);setOcrPages(current=>current.map(page=>page.extractionId===id?{...page,...updated,pageId:page.pageId}:page));}}/><Stack direction="row" justifyContent="flex-end"><Button onClick={()=>router.push("/worksheets")} sx={primary}>Confirm submission</Button></Stack></Box>}</Box></Box>; }
export default function Page() { return <React.Suspense fallback={null}><UploadWizard /></React.Suspense>; }
