"use client";

import * as React from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Card from "@mui/material/Card";
import Button from "@mui/material/Button";
import SwitchMui from "@mui/material/Switch";
import SchoolOutlinedIcon from "@mui/icons-material/SchoolOutlined";
import CalculateOutlinedIcon from "@mui/icons-material/CalculateOutlined";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import Link from "next/link";
import { student, initialsOf } from "@/lib/student-mock-data";
import Stack from "@/components/lumina-stack";

const buttonBase = { minHeight: 38, textTransform: "none", fontSize: 13, fontWeight: 500, borderRadius: "10px", "&:focus-visible": { outline: "3px solid #E08A72", outlineOffset: 2 } };
const Switch = SwitchMui as unknown as React.ComponentType<{
  checked: boolean;
  onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
  inputProps?: { "aria-label": string };
  sx: object;
}>;
function DetailRow({ label, value, last, mono }: { label: string; value: string; last?: boolean; mono?: boolean }) { return <Stack direction="row" gap={2} alignItems="center" justifyContent="space-between" sx={{ px: { xs: 2, sm: 2.75 }, py: 1.8, borderBottom: last ? 0 : "1px solid #F0EAE0" }}><Typography sx={{ fontSize: 13, color: "#6F675E" }}>{label}</Typography><Typography sx={{ fontSize: 13, fontWeight: 500, color: "#2A2622", fontFamily: mono ? "ui-monospace, SFMono-Regular, Menlo, monospace" : undefined }}>{value}</Typography></Stack>; }

export default function Page() {
  const [notifications, setNotifications] = React.useState(true);
  const [message, setMessage] = React.useState("");
  return <Box sx={{ minHeight: "100vh", bgcolor: "#F7F4EF", px: { xs: 2.5, sm: 3.75 }, py: 3.75, color: "#2A2622" }}><Box sx={{ maxWidth: 760, mx: "auto", animation: "fadeUp .35s ease both" }}>
    <Typography component="h1" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: { xs: 32, sm: 38 }, fontWeight: 500, lineHeight: 1.1, letterSpacing: "-.02em", mb: 3 }}>My Profile</Typography>
    <Card component="section" aria-label="Profile summary" variant="outlined" sx={{ borderColor: "#EBE4D9", bgcolor: "#FFFDFA", borderRadius: "14px", boxShadow: "none", p: { xs: 2.25, sm: 3 }, display: "flex", alignItems: { xs: "flex-start", sm: "center" }, flexDirection: { xs: "column", sm: "row" }, gap: 2, mb: 2.5 }}><Box aria-hidden="true" sx={{ width: 66, height: 66, borderRadius: "50%", flexShrink: 0, bgcolor: "#D8B384", display: "grid", placeItems: "center", fontFamily: "'Playfair Display', Georgia, serif", fontSize: 24, fontWeight: 600, color: "#3A332C" }}>{initialsOf(student.name)}</Box><Box sx={{ flex: 1 }}><Typography sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 28, lineHeight: 1.1 }}>{student.name}</Typography><Typography sx={{ fontSize: 13.5, color: "#6F675E", mt: .6 }}>Primary 5 · Lumina Academy</Typography></Box><Button onClick={() => setMessage("Profile editor selected.")} variant="outlined" sx={{ ...buttonBase, borderColor: "#E4DCD0", bgcolor: "#FFFDFA", color: "#2A2622", px: 2, "&:hover": { bgcolor: "#F4EFE6" } }}>Edit profile</Button></Card>
    <Card component="section" aria-labelledby="account-details" variant="outlined" sx={{ overflow: "hidden", borderColor: "#EBE4D9", bgcolor: "#FFFDFA", borderRadius: "14px", boxShadow: "none", mb: 2.5 }}><Typography id="account-details" component="h2" sx={{ px: { xs: 2, sm: 2.75 }, py: 1.8, borderBottom: "1px solid #EFE8DE", fontSize: 10.5, fontWeight: 600, letterSpacing: ".13em", color: "#A09488" }}>ACCOUNT DETAILS</Typography><DetailRow label="Full name" value={student.name} /><DetailRow label="Level / grade" value="Primary 5" /><DetailRow label="Student ID" value="LUM-2026-0148" mono last /></Card>
    <Card component="section" aria-labelledby="enrolled-subjects" variant="outlined" sx={{ overflow: "hidden", borderColor: "#EBE4D9", bgcolor: "#FFFDFA", borderRadius: "14px", boxShadow: "none", mb: 2.5 }}><Typography id="enrolled-subjects" component="h2" sx={{ px: { xs: 2, sm: 2.75 }, py: 1.8, borderBottom: "1px solid #EFE8DE", fontSize: 10.5, fontWeight: 600, letterSpacing: ".13em", color: "#A09488" }}>ENROLLED SUBJECTS</Typography><Stack component={Link} href="/subject-profile" direction="row" alignItems="center" gap={1.5} sx={{ minHeight: 70, px: { xs: 2, sm: 2.75 }, py: 1.6, borderBottom: "1px solid #F0EAE0", color: "inherit", textDecoration: "none", "&:hover": { bgcolor: "#FBF7F1" }, "&:focus-visible": { outline: "3px solid #E08A72", outlineOffset: -3 } }}><Box aria-hidden="true" sx={{ width: 36, height: 36, borderRadius: "9px", bgcolor: "#EAEDE7", color: "#4A6B50", display: "grid", placeItems: "center" }}><SchoolOutlinedIcon sx={{ fontSize: 18 }} /></Box><Box sx={{ flex: 1, minWidth: 0 }}><Typography sx={{ fontSize: 14.5, fontWeight: 600 }}>Science</Typography><Typography sx={{ fontSize: 12.5, color: "#8B837A" }}>Primary 5 · Prof. E. Vance</Typography></Box><ArrowForwardIcon aria-hidden="true" sx={{ color: "#B4573F", fontSize: 18 }} /></Stack><Stack direction="row" alignItems="center" gap={1.5} sx={{ minHeight: 70, px: { xs: 2, sm: 2.75 }, py: 1.6 }}><Box aria-hidden="true" sx={{ width: 36, height: 36, borderRadius: "9px", bgcolor: "#F4EFE6", color: "#8B837A", display: "grid", placeItems: "center" }}><CalculateOutlinedIcon sx={{ fontSize: 18 }} /></Box><Box><Typography sx={{ fontSize: 14.5, fontWeight: 600 }}>Mathematics</Typography><Typography sx={{ fontSize: 12.5, color: "#8B837A" }}>Enrolling next term</Typography></Box></Stack></Card>
    <Card component="section" aria-labelledby="security" variant="outlined" sx={{ overflow: "hidden", borderColor: "#EBE4D9", bgcolor: "#FFFDFA", borderRadius: "14px", boxShadow: "none" }}><Typography id="security" component="h2" sx={{ px: { xs: 2, sm: 2.75 }, py: 1.8, borderBottom: "1px solid #EFE8DE", fontSize: 10.5, fontWeight: 600, letterSpacing: ".13em", color: "#A09488" }}>PASSWORD &amp; SECURITY</Typography><Stack direction="row" gap={2} alignItems="center" justifyContent="space-between" sx={{ px: { xs: 2, sm: 2.75 }, py: 1.8, borderBottom: "1px solid #F0EAE0" }}><Box><Typography sx={{ fontSize: 13.5, fontWeight: 500 }}>Password</Typography><Typography sx={{ fontSize: 12.5, color: "#8B837A", mt: .25 }}>Last changed 2 months ago</Typography></Box><Button onClick={() => setMessage("Password change selected.")} variant="outlined" sx={{ ...buttonBase, minHeight: 34, borderColor: "#E4DCD0", color: "#6F675E", px: 1.7, "&:hover": { bgcolor: "#F4EFE6" } }}>Change</Button></Stack><Stack direction="row" gap={2} alignItems="center" justifyContent="space-between" sx={{ px: { xs: 2, sm: 2.75 }, py: 1.8 }}><Box><Typography sx={{ fontSize: 13.5, fontWeight: 500 }}>Notifications</Typography><Typography sx={{ fontSize: 12.5, color: "#8B837A", mt: .25 }}>Get told when marking and tutor replies are ready.</Typography></Box><Switch checked={notifications} onChange={(event) => { setNotifications(event.target.checked); setMessage(`Notifications ${event.target.checked ? "on" : "off"}.`); }} inputProps={{ "aria-label": "Notifications" }} sx={{ width: 46, height: 28, p: 0, ".MuiSwitch-switchBase": { p: "4px", "&.Mui-checked": { transform: "translateX(18px)", color: "#FFFDFA", "+ .MuiSwitch-track": { bgcolor: "#9E3A24", opacity: 1 } } }, ".MuiSwitch-thumb": { width: 20, height: 20 }, ".MuiSwitch-track": { borderRadius: 20, bgcolor: "#DED5C8", opacity: 1 } }} /></Stack></Card>
    <Box role="status" aria-live="polite" sx={{ position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0 0 0 0)" }}>{message}</Box>
  </Box></Box>;
}
