services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PW:?POSTGRES_PW is required}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is required}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy


  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AUTH_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:?POSTGRES_DB is required}
      AUTH_DB_USERNAME: ${POSTGRES_USER:?POSTGRES_USER is required}
      AUTH_DB_PASSWORD: ${POSTGRES_PW:?POSTGRES_PW is required}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:?JWT_EXPIRATION_MS is required}

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://auth-service:8081  # Connects to backend using Docker service name
  #   depends_on:
  #     auth-service:
  #       condition: service_started

volumes:
  postgres_data:
