services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy


  # auth-service:
  #   build: ./backend/auth-service
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     # These override the application.properties values
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
  #     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
  #     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PW}

volumes:
  postgres_data: