"use client";

import * as React from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import Chip from "@mui/material/Chip";
import Skeleton from "@mui/material/Skeleton";
import Typography from "@mui/material/Typography";
import Link from "next/link";
import { dismissTutorAlert, fetchTutorAlerts, resolveTutorAlert, type TutorAlert } from "@/services/alerts";

const severity = { INFO: { bg: "#F0EAE0", color: "#6F675E", label: "MONITOR" }, WARNING: { bg: "#F7E3DC", color: "#9E3A24", label: "NEEDS PRACTICE" }, CRITICAL: { bg: "#F7E3DC", color: "#9E3A24", label: "HIGH PRIORITY" } } as const;
export default function AlertList({ loadAlerts = fetchTutorAlerts, resolve = resolveTutorAlert, dismiss = dismissTutorAlert }: { loadAlerts?: () => Promise<TutorAlert[]>; resolve?: (id: number) => Promise<TutorAlert>; dismiss?: (id: number) => Promise<TutorAlert> }) {
  const [alerts, setAlerts] = React.useState<TutorAlert[] | null>(null); const [error, setError] = React.useState<string | null>(null); const [busy, setBusy] = React.useState<number | null>(null);
  const load = React.useCallback(async () => { setError(null); try { setAlerts(await loadAlerts()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Alerts could not be loaded."); } }, [loadAlerts]);
  React.useEffect(() => { let current = true; const request = async () => { try { const loaded = await loadAlerts(); if (current) setAlerts(loaded); } catch (caught) { if (current) setError(caught instanceof Error ? caught.message : "Alerts could not be loaded."); } }; void request(); return () => { current = false; }; }, [loadAlerts]);
  const act = async (item: TutorAlert, action: (id: number) => Promise<TutorAlert>) => { setBusy(item.id); setError(null); try { const changed = await action(item.id); setAlerts((current) => (current ?? []).filter((value) => value.id !== changed.id)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Alert could not be updated."); } finally { setBusy(null); } };
  if (!alerts && !error) return <Box aria-label="Loading alerts" sx={{ display: "grid", gap: 1.25 }}>{[0, 1, 2].map((value) => <Card key={value} variant="outlined" sx={{ p: 2, bgcolor: "#FFFDFA", borderColor: "#EBE4D9" }}><Skeleton height={26} width="40%" /><Skeleton height={44} /></Card>)}</Box>;
  if (error) return <Card component="section" role="alert" variant="outlined" sx={{ p: 3, maxWidth: 560, bgcolor: "#FFFDFA", borderColor: "#EBE4D9", borderLeft: "3px solid #B4573F" }}><Typography component="h2" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 21 }}>Alerts could not be loaded</Typography><Typography sx={{ mt: .75, color: "#5A544C" }}>{error}</Typography><Button onClick={() => void load()} variant="outlined" sx={{ mt: 1.5, textTransform: "none", borderColor: "#E4DCD0", color: "#2A2622" }}>Try again</Button></Card>;
  if (!alerts?.length) return <Card component="section" variant="outlined" sx={{ textAlign: "center", p: 4, minHeight: 280, display: "grid", placeItems: "center", bgcolor: "#FFFDFA", border: "1px dashed #DCCFBE" }}><Box><Typography component="h2" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 23 }}>No active alerts</Typography><Typography sx={{ color: "#8B837A", mt: .75 }}>New tutor actions will appear here when evidence needs attention.</Typography></Box></Card>;
  return <Box sx={{ display: "grid", gap: 1.25 }}>{alerts.map((item) => { const token = severity[item.severity]; return <Card key={item.id} component="article" variant="outlined" sx={{ p: { xs: 2, sm: 2.25 }, bgcolor: "#FFFDFA", borderColor: "#EBE4D9", borderRadius: "12px", boxShadow: "none" }}><Box sx={{ display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: 1 }}><Box sx={{ minWidth: 0, flex: "1 1 280px" }}><Typography component="h2" sx={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 21 }}>{item.title}</Typography><Typography sx={{ color: "#6F675E", fontSize: 13.5, mt: .5, lineHeight: 1.55 }}>{item.message}</Typography><Typography sx={{ color: "#8B837A", fontSize: 12, mt: .9 }}>Student: <Link href={`/students/${item.studentId}`} style={{ color: "inherit" }}>{item.studentName}</Link></Typography></Box><Chip label={token.label} size="small" sx={{ bgcolor: token.bg, color: token.color, fontWeight: 700, fontSize: 10, letterSpacing: ".04em" }} /></Box><Box sx={{ display: "flex", flexWrap: "wrap", gap: 1, mt: 1.5 }}><Button onClick={() => void act(item, resolve)} disabled={busy !== null} sx={{ minHeight: 36, textTransform: "none", bgcolor: "#9E3A24", color: "#FFFDFA", "&:hover": { bgcolor: "#8A3120" } }}>Resolve alert</Button><Button onClick={() => void act(item, dismiss)} disabled={busy !== null} variant="outlined" sx={{ minHeight: 36, textTransform: "none", borderColor: "#E4DCD0", color: "#5A544C" }}>Dismiss alert</Button></Box></Card>; })}</Box>;
}
