import { beforeEach, describe, expect, it, vi } from "vitest"; import { MAX_UPLOAD_BYTES, approveMarkingReview, createManualResult, createMarkingReview, fetchMarkingReview, parseMarkingReview, submitSubmission, validateUploadFiles } from "./submissions";
const file = (name: string, type = "image/jpeg", size = 4) => new File([new Uint8Array(size)], name, { type, lastModified: 1 });
describe("submissions service", () => { beforeEach(() => { vi.stubGlobal("URL", { createObjectURL: vi.fn(() => "blob:page"), revokeObjectURL: vi.fn() }); vi.stubGlobal("fetch", vi.fn()); }); it("accepts images and PDFs while rejecting invalid, duplicate, empty and oversized files", () => { const first = file("one.jpg"); expect(validateUploadFiles([first, file("two.pdf", "application/pdf")]).pages).toHaveLength(2); expect(validateUploadFiles([first], validateUploadFiles([first]).pages).errors[0]).toMatch(/already/); expect(validateUploadFiles([file("bad.gif", "image/gif"), file("empty.jpg", "image/jpeg", 0), file("large.jpg", "image/jpeg", MAX_UPLOAD_BYTES + 1)]).errors).toHaveLength(3); }); it("uploads reviewed pages with progress and preserves server errors", async () => { const pages = validateUploadFiles([file("one.jpg"), file("two.png", "image/png")]).pages; vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({ extracted_text: "ok" }), { status: 200 })); const progress = vi.fn(); await expect(submitSubmission("ws1", pages, progress)).resolves.toMatchObject({ pageCount: 2 }); expect(progress).toHaveBeenLastCalledWith(2, 2); }); it("loads and validates tutor marking reviews before approval", async () => { const review = { id: 1, studentId: 2, worksheetId: 3, worksheetQuestionId: 4, questionBankId: 5, extractedAnswer: "Answer", modelAnswer: "Model", maxMarks: 2, aiSuggestedMarks: 1, aiSuggestedOutcome: "Partial", aiErrorCategory: null, missingKeywords: [], aiSuggestedFeedback: "Feedback", reviewStatus: "PENDING_REVIEW", approvedMarks: null, approvedFeedback: null, reviewedByUserId: null, reviewedAt: null, providerResponseValid: true, history: [] }; vi.mocked(fetch).mockResolvedValueOnce(new Response(JSON.stringify(review), { status: 200 })).mockResolvedValueOnce(new Response(JSON.stringify({ ...review, reviewStatus: "APPROVED", approvedMarks: 2, approvedFeedback: "Tutor feedback" }), { status: 200 })).mockResolvedValueOnce(new Response(JSON.stringify(review), { status: 201 })); await expect(fetchMarkingReview(1)).resolves.toMatchObject({ id: 1, reviewStatus: "PENDING_REVIEW" }); await expect(approveMarkingReview(1, 2, "Tutor feedback")).resolves.toMatchObject({ reviewStatus: "APPROVED" }); await expect(createMarkingReview({ submissionDocumentId: 8, worksheetQuestionId: 4, questionBankId: 5 })).resolves.toMatchObject({ id: 1 }); expect(fetch).toHaveBeenLastCalledWith(expect.stringContaining("/tutor/reviews"), expect.objectContaining({ method: "POST" })); expect(() => parseMarkingReview({ id: 1 })).toThrow(/invalid/i); }); });

describe("manual result client", () => {
  it("posts a validated manual result and rejects missing required values locally", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ id: 1, studentId: 2, worksheetId: 3, worksheetQuestionId: 5, questionBankId: 5, extractedAnswer: "Answer", modelAnswer: "Model", maxMarks: 2, aiSuggestedMarks: null, aiSuggestedOutcome: null, aiErrorCategory: null, missingKeywords: [], aiSuggestedFeedback: null, reviewStatus: "APPROVED", approvedMarks: 1.5, approvedFeedback: "Tutor feedback", reviewedByUserId: 1, reviewedAt: "2026-08-27T10:00:00", providerResponseValid: null, history: [] }), { status: 201 })));
    await expect(createManualResult({ worksheetId: 3, studentId: 2, questionBankId: 5, answer: "Answer", marks: 1.5, feedback: "Tutor feedback" })).resolves.toMatchObject({ reviewStatus: "APPROVED" });
    expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/tutor/reviews/manual"), expect.objectContaining({ method: "POST" }));
    await expect(createManualResult({ worksheetId: 3, studentId: 2, questionBankId: 5, answer: "", marks: 1.5, feedback: "Tutor feedback" })).rejects.toMatchObject({ status: 400 });
  });
});
