spring.application.name=grading-service
# Server configuration
server.port=8082

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate auto-generation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Groq API Configuration
ai.engine.url=https://api.groq.com/openai/v1/chat/completions
ai.engine.model=openai/gpt-oss-20b
ai.engine.api-key=
ai.vision.model=qwen/qwen3.6-27b